#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)
np.show_config()

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/aleks/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/aleks/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/aleks/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
Vec = np.zeros(10)
Vec

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
Arr = np.zeros((10,10))
Arr.size * Arr.itemsize

800

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [5]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
Vec = np.zeros(10)
Vec[4] = 1
Vec

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
Vec = np.arange(10,50)
Vec

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [8]:
RevVec = np.arange(50)
RevVec = Vec[::-1]
RevVec

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
Matr = np.arange(9).reshape(3, 3)
Matr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [10]:
nz_elem = np.nonzero([1,2,0,0,4,0])
nz_elem

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [11]:
Id = np.eye(3)
Id

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [12]:
RandMatr = np.random.random((3,3))
RandMatr

array([[0.36384311, 0.99697418, 0.66487834],
       [0.85225635, 0.91509289, 0.43506404],
       [0.93505469, 0.33298226, 0.65508338]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
Matr = np.random.random((10,10))
Matr_min, Matr_max = Matr.min(), Matr.max()
Matr, Matr_min, Matr_max

(array([[0.76492974, 0.18454783, 0.09141199, 0.3911708 , 0.67980201,
         0.52097454, 0.52361872, 0.11789143, 0.80649901, 0.56383636],
        [0.81730187, 0.75057954, 0.45685347, 0.16533288, 0.76587385,
         0.00598243, 0.24921097, 0.729569  , 0.24038015, 0.90749876],
        [0.53586274, 0.08679141, 0.62673221, 0.47918373, 0.79008766,
         0.43196356, 0.30644469, 0.13342925, 0.51625287, 0.50707335],
        [0.65034153, 0.32544716, 0.98316324, 0.33234597, 0.43410301,
         0.05073179, 0.30356497, 0.75967246, 0.02960761, 0.64244489],
        [0.20736363, 0.09912014, 0.34623996, 0.0398642 , 0.51123983,
         0.67926598, 0.05715398, 0.50859557, 0.8231679 , 0.72468454],
        [0.96414142, 0.36983281, 0.14314601, 0.43932841, 0.51721691,
         0.69548739, 0.29672276, 0.32945346, 0.33978822, 0.13954915],
        [0.03645426, 0.71295607, 0.5356926 , 0.6617153 , 0.05566476,
         0.56494564, 0.53551015, 0.13575924, 0.43137284, 0.60246349],
        [0.54512629, 0.4549

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [14]:
Vec = np.random.random(30)
mean = Vec.mean()
mean

0.5192387063055627

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [15]:
Twod = np.ones((10,10))
Twod[1:-1,1:-1] = 0
Twod

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [16]:
x = np.pad(Twod, pad_width=1, mode='constant', constant_values=0)
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [17]:
0 * np.nan, np.nan == np.nan, np.inf > np.nan, np.nan - np.nan, np.nan in set([np.nan]), 0.3 == 3 * 0.1

(nan, False, False, nan, True, False)

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [18]:
Matr = np.diag(1+np.arange(4),k=-1)
Matr

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [19]:
Matrix = np.zeros((8,8),dtype=int)
Matrix[1::2,::2] = 1
Matrix[::2,1::2] = 1
Matrix

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [20]:
np.unravel_index(99,(6,7,8))

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [21]:
Chess = np.tile( np.array([[0,1],[1,0]]), (4,4))
Chess

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [22]:
Matr = np.random.random((5,5))
Matr_max, Matr_min = Matr.max(), Matr.min()
Matr = (Matr-Matr_min)/(Matr_max-Matr_min)
Matr

array([[0.70090114, 0.44151777, 0.        , 0.33333215, 0.19795861],
       [0.36571513, 0.74464347, 0.2200077 , 0.40368076, 1.        ],
       [0.62537845, 0.63673943, 0.81871639, 0.88330838, 0.17085754],
       [0.78046431, 0.54287205, 0.22896181, 0.07399898, 0.98342782],
       [0.05804532, 0.82525978, 0.82187288, 0.45398719, 0.6484818 ]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [23]:
colour = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
colour

C:\Users\aleks\anaconda3\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [24]:
Prod = np.ones((5,3)) @ np.ones((3,2))
Prod

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [25]:
OneD = np.arange(11)
OneD[(3 < OneD) & (OneD < 8)] *= -1
OneD

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [26]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [70]:
Z=np.array([1,2])
Z**Z, Z <- Z, 1j*Z, Z/1/1
# 2 << Z >> 2 illegal 
# Z<Z>Z illegal

(array([1, 4], dtype=int32),
 array([False, False]),
 array([0.+1.j, 0.+2.j]),
 array([1., 2.]))

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [30]:
np.array(0) / np.array(0), np.array(0) // np.array(0), np.array([np.nan]).astype(int).astype(float)

C:\Users\aleks\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\Users\aleks\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


(nan, 0, array([-2.14748365e+09]))

#### 29. How to round away from zero a float array ? (★☆☆)

In [31]:
Arr = np.random.uniform(-10,+10,10)
np.copysign(np.ceil(np.abs(Arr)), Arr)

array([ 4., 10., -6., -9., -4., -3., -2., -7.,  5., -6.])

#### 30. How to find common values between two arrays? (★☆☆)

In [32]:
Matr_1 = np.random.randint(0,10,10)
Matr_2 = np.random.randint(0,10,10)
np.intersect1d(Matr_1,Matr_2)

array([0, 1, 5, 6, 7, 9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [33]:
defaults = np.seterr(all="ignore")
Omg = np.ones(1) / 0
Omg

array([inf])

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [34]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [35]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
yesterday, today, tomorrow

(numpy.datetime64('2020-12-12'),
 numpy.datetime64('2020-12-13'),
 numpy.datetime64('2020-12-14'))

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [36]:
July = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
July

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [37]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B), np.divide(A,2,out=A), np.negative(A,out=A), np.multiply(A,B,out=A)

(array([3., 3., 3.]),
 array([-1.5, -1.5, -1.5]),
 array([-1.5, -1.5, -1.5]),
 array([-1.5, -1.5, -1.5]))

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [38]:
Ex = np.random.uniform(0,10,10)
Ex - Ex%1, Ex // 1, np.floor(Ex), Ex.astype(int), np.trunc(Ex)

(array([9., 7., 8., 2., 2., 0., 1., 7., 0., 7.]),
 array([9., 7., 8., 2., 2., 0., 1., 7., 0., 7.]),
 array([9., 7., 8., 2., 2., 0., 1., 7., 0., 7.]),
 array([9, 7, 8, 2, 2, 0, 1, 7, 0, 7]),
 array([9., 7., 8., 2., 2., 0., 1., 7., 0., 7.]))

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [39]:
Matr = np.zeros((5,5))
Matr += np.arange(5)
Matr

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [40]:
def generate(): 
    for x in range(10):
        yield x
        
Arr = np.fromiter(generate(), dtype=float, count=-1)
Arr

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [41]:
Vector = np.linspace(0,1,12,endpoint=True)[1:-1]
Vector

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [42]:
SortVec = np.random.random(10)
SortVec.sort()
SortVec

array([0.13196036, 0.16671813, 0.19555945, 0.26388379, 0.31899133,
       0.3246333 , 0.37560845, 0.45007205, 0.58068083, 0.58550795])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [43]:
Arr = np.arange(10)
np.add.reduce(Arr)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [44]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
equal

False

#### 43. Make an array immutable (read-only) (★★☆)

In [45]:
Arr = np.zeros(10)
Arr.flags.writeable = False
Arr[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [46]:
DecCor = np.random.random((10,2))
X,Y = DecCor[:,0], DecCor[:,1]
R = np.sqrt(X**2+Y**2)
Phi = np.arctan2(Y,X)
R, Phi

(array([0.22033689, 0.38368817, 1.08688722, 0.65457964, 1.22845585,
        0.77003686, 0.15015436, 1.07977702, 0.3088097 , 0.97552177]),
 array([0.85149594, 1.15720637, 0.95257938, 0.20352186, 0.77142562,
        1.08615323, 0.92500146, 1.07170805, 0.01037308, 1.21519591]))

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [47]:
Vec = np.random.random(10)
Vec[Vec.argmax()] = 0
Vec

array([0.        , 0.33336175, 0.80218876, 0.4406758 , 0.34520864,
       0.63456118, 0.12991199, 0.26104482, 0.17970787, 0.77931454])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [48]:
Arr = np.zeros((5,5), [('x',float),('y',float)])
Arr['x'], Arr['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
Arr

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [49]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
C, np.linalg.det(C)

(array([[-2.        , -0.66666667, -0.4       , -0.28571429, -0.22222222,
         -0.18181818, -0.15384615, -0.13333333],
        [ 2.        , -2.        , -0.66666667, -0.4       , -0.28571429,
         -0.22222222, -0.18181818, -0.15384615],
        [ 0.66666667,  2.        , -2.        , -0.66666667, -0.4       ,
         -0.28571429, -0.22222222, -0.18181818],
        [ 0.4       ,  0.66666667,  2.        , -2.        , -0.66666667,
         -0.4       , -0.28571429, -0.22222222],
        [ 0.28571429,  0.4       ,  0.66666667,  2.        , -2.        ,
         -0.66666667, -0.4       , -0.28571429],
        [ 0.22222222,  0.28571429,  0.4       ,  0.66666667,  2.        ,
         -2.        , -0.66666667, -0.4       ],
        [ 0.18181818,  0.22222222,  0.28571429,  0.4       ,  0.66666667,
          2.        , -2.        , -0.66666667],
        [ 0.15384615,  0.18181818,  0.22222222,  0.28571429,  0.4       ,
          0.66666667,  2.        , -2.        ]]),
 3638.16363711

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [50]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [51]:
np.set_printoptions(threshold=float("inf"))
Matrix = np.zeros((16,16))
Matrix

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [52]:
Vec = np.arange(100)
Matr = np.random.uniform(0,100)
index = (np.abs(Vec-Matr)).argmin()
print(Vec[index])

29


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [53]:
Rgb = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('colour',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
Rgb

C:\Users\aleks\anaconda3\lib\site-packages\ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('colour', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [54]:
Vec = np.random.random((100,2))
X,Y = np.atleast_2d(Vec[:,0], Vec[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.49050717 0.51897714 0.60486169 0.37737244 0.60994532
  0.46197959 0.21396291 0.21983226 0.3570678  0.19248003 0.82141011
  0.45842574 0.19747771 0.65926238 0.08758815 0.363869   0.56861194
  0.23079768 0.76967087 0.37653585 0.32959406 0.17132106 0.67831921
  0.62349579 0.51806749 0.36780916 0.48826335 0.01648796 0.52501111
  0.53871836 0.3870766  0.54418332 0.70740945 0.31291111 0.1863735
  0.04335834 0.62889863 0.46356524 0.70042278 0.3640413  0.5539048
  0.32454771 0.56309196 0.29857835 0.27861808 0.58992433 0.06566358
  0.43544066 0.58260515 0.34761123 0.58292249 0.59146031 0.69186893
  0.46428991 0.59004479 0.38693386 0.55547679 0.2480263  0.18595945
  0.46019672 0.30239124 0.70711737 0.91825211 0.57755644 0.3352771
  0.38164927 0.76036049 0.2411982  0.75508696 0.03428903 0.40997035
  0.63059789 0.38306962 0.56521215 0.26944756 0.15506776 0.4460187
  0.47687687 0.6520144  0.51795428 0.40428175 0.49816978 0.61020054
  0.48120843 0.57113146 0.43219934 0.67862721 0.5359

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [55]:
Matr = (np.random.rand(10)*100).astype(np.float32)
Int = Matr.view(np.int32)
Int[:] = Matr
Int

array([43, 34, 76, 31, 91, 63, 45, 19, 99, 97])

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [72]:
Read = np.genfromtxt(fname,delimiter=",")

NameError: name 'fname' is not defined

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [57]:
Arr = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Arr):
    print(index, value)
for index in np.ndindex(Arr.shape):
    print(index, Arr[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [58]:
x, y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(x * x + y * y)
sigma, mu = 1.0, 0.0
G = np.exp(- ( (D - mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [59]:
n = 10
p = 3
Matr = np.zeros((n,n))
np.put(Matr, np.random.choice(range(n*n), p, replace=False),1)
Matr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [136]:
Arr = np.random.rand(5, 10)
Y = Arr - Arr.mean(axis=1, keepdims=True)
Y

array([[ 0.40399365, -0.2776867 ,  0.04217292, -0.18422548,  0.09531516,
        -0.28616004,  0.04175086, -0.41124691,  0.37560569,  0.20048086],
       [-0.37351094, -0.47620564, -0.22745166,  0.02741766, -0.23826041,
         0.4476493 ,  0.49738666, -0.01202486,  0.11979346,  0.23520644],
       [ 0.53208836, -0.07881121, -0.14023632,  0.00968997,  0.26371755,
         0.34115464, -0.22527355, -0.40758673, -0.0307556 , -0.26398711],
       [ 0.31590784, -0.19692673,  0.19781369, -0.39694346,  0.03844368,
         0.1264292 ,  0.33678619,  0.17525037, -0.17624494, -0.42051583],
       [-0.14042385,  0.51912445, -0.12926336, -0.28342554, -0.13830891,
        -0.38395578,  0.44852797,  0.43211512, -0.14156209, -0.182828  ]])

#### 59. How to sort an array by the nth column? (★★☆)

In [60]:
Matr = np.random.randint(0,10,(3,3))
print(Matr)
print(Matr[Matr[:,1].argsort()])

[[7 4 8]
 [9 6 8]
 [2 2 0]]
[[2 2 0]
 [7 4 8]
 [9 6 8]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [61]:
Matr = np.random.randint(0,3,(3,10))
print(Matr)
print((~Matr.any(axis=0)).any())

[[2 1 1 0 2 2 0 2 2 2]
 [2 2 2 2 2 1 0 0 2 2]
 [0 2 0 1 1 2 2 0 0 0]]
False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [62]:
Matr = np.random.uniform(0,1,10)
delta = 0.5
m = Matr.flat[np.abs(Matr - delta).argmin()]
print(m)

0.4489555465730788


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [63]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(A, B)
print(it.operands[2])

[[0]
 [1]
 [2]] [[0 1 2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [65]:
class NamedArray(np.ndarray):
    def __new__(cls, arr, name="no name"):
        objective = np.asarray(arr).view(cls)
        objective.name = name
        return objective
    def __array_finalize__(self, objective):
        if objective is None: return
        self.info = getattr(objective, 'name', "no name")

Matrix = NamedArray(np.arange(10), "Matrix10")
print (Matrix.name)

Matrix10
